---
title: "1. Indian Economy on the Eve of Independence"
author: "pravesh"
date: "2020-09-15"
output: html_document
---

## Reference
- [NCERT Text Book](https://ncert.nic.in/ncerts/l/keec101.pdf) Chapter 1.

<iframe width="560" height="315" src="https://www.youtube.com/embed/51o2E9zjUE4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/tUC__A9hENg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Introduction
- A look at the state of India’s economy prior to the country’s independence and form an idea of the various considerations that shaped India’s post-independence development strategy.
- The structure of India’s present-day economy is not just of current making; it has its roots steeped in history, particularly in the period when India was under British rule which lasted for almost two centuries before India finally won its independence on 15 August 1947. 

## Low level of economic development under the colonial rule.
- India had an independent economy before the advent of the British rule.
- Though agriculture was the main source of livelihood for most people, yet, the country’s economy was characterised by various kinds of manufacturing activities. - India was particularly well known for its handicraft industries in the fields of cotton and silk textiles, metal and precious stone works etc. These products enjoyed a worldwide market based on the reputation of the fine quality of material used and the high standards of craftsmanship seen in all imports from India.
- The economic policies pursued by the colonial government in India were concerned more with the protection and promotion of the economic interests of their home country than with the development of the Indian economy. Such policies brought about a fundamental change in the structure of the Indian economy — transforming the country into supplier of raw materials and consumer of finished industrial products from Britain.
- Obviously, the colonial government never made any sincere attempt to estimate India’s national and per capita income.
- However few individuals such as Dadabhai Naoroji, William Digby, Findlay Shirras, V.K.R.V. Rao and R.C. Desai estimated national income.
- However, most studies did find that the country’s growth of aggregate real output during the first half of the twentieth century was less than two per cent coupled with a meagre half per cent growth in per capita output per year.

## Agricultural sector
- India’s economy under the British colonial rule remained fundamentally agrarian — about 85 per cent of the country’s population lived mostly in villages and derived livelihood directly or indirectly from agriculture.
- continued to experience stagnation and, not infrequently, unusual deterioration. Agricultural productivity became low though, in absolute terms, the sector experienced some growth due to the expansion of the aggregate area under cultivation. 
- This stagnation in the agricultural sector was caused mainly because of the various systems of land settlement that were introduced by the colonial government. Particularly, under the zamindari system which was implemented in the then Bengal Presidency comprising parts of India’s present-day eastern states, the profit accruing out of the agriculture sector went to the zamindars instead of the cultivators. 
- However, a considerable number of zamindars, and not just the colonial government, did nothing to improve the condition of agriculture.
- The main interest of the zamindars was only to collect rent regardless of the economic condition of the cultivators; this caused immense misery and social tension among the latter. 
- To a very great extent, the terms of the revenue settlement were also responsible for the zamindars adopting such an attitude; dates for depositing specified sums of revenue were fixed, failing which the zamindars were to lose their rights. 
- Besides this, low levels of technology, lack of irrigation facilities and negligible use of fertilisers, all added up to aggravate the plight of the farmers and contributed to the dismal level of agricultural productivity. 
- There was, of course, some evidence of a relatively higher yield of cash crops in certain areas of the country due to commercialisation of agriculture.

## Industrial sector
- India could not develop a sound industrial base under the colonial rule. Even as the country’s world famous handicraft industries declined, no corresponding modern industrial base was allowed to come up to take pride of place so long enjoyed by the former. 
- The primary motive of the colonial government behind this policy of systematically deindustrialising India was two-fold. 
- The intention was, first, to reduce India to the status of a mere exporter of important raw materials for the upcoming modern industries in Britain and, second, to turn India into a sprawling market for the finished products of those industries so that their continued expansion could be ensured to the maximum advantage of their home country — Britain. 
- The decline of the indigenous handicraft industries created not only massive unemployment in India but also a new demand in the Indian consumer market, which was now deprived of the supply of locally made goods. This demand was profitably met by the increasing imports of cheap manufactured goods from Britain.
- During the second half of the nineteenth century, modern industry began to take root in India but its progress remained very slow. 
- Initially, this development was confined to the setting up of cotton and jute textile mills. The cotton textile mills, mainly dominated by Indians, were located in the western parts of the country, namely, Maharashtra and Gujarat, while the jute mills dominated by the foreigners were mainly concentrated in Bengal. 
- Subsequently, the iron and steel industries began coming up in the beginning of the twentieth century. The Tata Iron and Steel Company (TISCO) was incorporated in 1907. A few other industries in the fields of sugar, cement, paper etc. came up after the Second World War.
- However, there was hardly any capital goods industry to help promote further industrialisation in India. Capital goods industry means industries which can produce machine tools which are, in turn, used for producing articles for current consumption. The establishment of a few manufacturing units here and there was no substitute to the near wholesale displacement of the country’s traditional handicraft industries. Furthermore, the growth rate of the new industrial sector and its contribution to the Gross Domestic Product (GDP) remained very small.
- Another significant drawback of the new industrial sector was the very limited area of operation of the public sector. This sector remained confined only to the railways, power generation, communications, ports and some other departmental undertakings.

## Foreign trade
- India has been an important trading nation since ancient times. But the restrictive policies of commodity production, trade and tariff pursued by the colonial government adversely affected the structure, composition and volume of India’s foreign trade.
- India was exporter of primary products such as raw silk, cotton, wool, sugar, indigo, jute etc. and an importer of finished consumer goods like cotton, silk and woollen clothes and capital goods like light machinery produced in the factories of Britain.
- More than half of India’s foreign trade was restricted to Britain while the rest was allowed with a few other countries like China, Ceylon (Sri Lanka) and Persia (Iran).
- The export surplus did not result in any flow of gold or silver into India. Rather, this was used to make payments for the expenses incurred by an office set up by the colonial government in Britain, expenses on war, again fought by the British government, and the import of invisible items, all of which led to the drain of Indian wealth.

## Demographic condition
- The survey on population of British India were first done through a census in 1881. It revealed an unevenness in the population growth.
- Every ten years such census operations were carried out. Before 1921, India was in the first stage of demographic transition. The second stage of transition began after 1921. However, neither the total population of India nor the rate of population growth at this stage was very high.
- The various social development indicators were also not quite encouraging. The overall literacy level was less than 16 per cent. Out of this, the female literacy level was at a negligible low of about seven per cent. 
- Public health facilities were either unavailable to large chunks of population or, when available, were highly inadequate. Consequently, water and air-borne diseases were rampant and took a huge toll on life. No wonder, the overall mortality rate was very high and in that, particularly, the infant mortality rate was quite alarming—about 218 per thousand in contrast to the present infant mortality rate of 63 per thousand. Life expectancy was also very low—44 years in contrast to the present 66 years. 
- In the absence of reliable data, it is difficult to specify the extent of poverty at that time but there is no doubt that extensive poverty prevailed in India during the colonial period which contributed to the worsening profile of India’s population of the time.

## Occupational structure
- The agricultural sector accounted for the largest share of workforce, which usually remained at a high of 70-75 per cent while the manufacturing and the services sectors accounted for only 10 and 15-20 per cent respectively.
- Another striking aspect was the growing regional variation. 
- Parts of the then Madras Presidency (comprising areas of the present-day states of Tamil Nadu, Andhra Pradesh, Kerala and Karnataka), Bombay and Bengal witnessed a decline in the dependence of the workforce on the agricultural sector with a commensurate increase in the manufacturing and the services sectors. However, there had been an increase in the share of workforce in agriculture during the same time in states such as Orissa, Rajasthan and Punjab.

## Infrastructure
- Under the colonial regime, basic infrastructure such as railways, ports, water transport, posts and telegraphs did develop. However, the real motive behind this development was not to provide basic amenities to the people but to subserve various colonial interests. 
- Roads constructed in India prior to the advent of the British rule were not fit for modern transport. The roads that were built primarily served the purposes of mobilising the army within India and drawing out raw materials from the countryside to the nearest railway station or the port to send these to far away England or other lucrative foreign destinations. 
- The British introduced the railways in India in 1850 and it is considered as one of their most important contributions. 
- The railways affected the structure of the Indian economy in two important ways. 
- On the one hand it enabled people to undertake long distance travel and thereby break geographical and cultural barriers while, on the other hand, it fostered commercialisation of Indian agriculture which adversely affected the self-sufficiency of the village economies in India. 
- The volume of India’s exports undoubtedly expanded but its benefits rarely accrued to the Indian people.
- The social benefits, which the Indian people gained owing to the introduction of the railways, were thus outweighed by the country’s huge economic loss.

